In [8]:
import numpy as np
a=np.array([10,20,30,40,50])
b=np.array([[10,20,30,40,50],[60,70,80,90,99]])


In [9]:
print("One dimensional array ",a)

One dimensional array  [10 20 30 40 50]


In [10]:
print("Two dimensional array ",b)


Two dimensional array  [[10 20 30 40 50]
 [60 70 80 90 99]]


In [11]:
c=np.zeros((3,4))


In [12]:
print("Array with all Zeros \n",c)


Array with all Zeros 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [13]:
d=np.random.random((3,4))


In [14]:
print("Array with random numbers \n",d)


Array with random numbers 
 [[0.60994938 0.21470384 0.1746524  0.52948696]
 [0.86818321 0.78433101 0.21262207 0.76323322]
 [0.35406255 0.13456493 0.46551034 0.69319471]]


In [15]:
e=np.arange(0,10,1)


In [16]:
print("Array with range value \n",e)


Array with range value 
 [0 1 2 3 4 5 6 7 8 9]


In [17]:
f=np.array([[1,2,3,0],[7,5,9,8],[4,8,6,2]])
g=f.reshape((4,3))

In [18]:
print("Original array : \n",f)
print("\n Reshaped array : \n",g)

Original array : 
 [[1 2 3 0]
 [7 5 9 8]
 [4 8 6 2]]

 Reshaped array : 
 [[1 2 3]
 [0 7 5]
 [9 8 4]
 [8 6 2]]


In [19]:
h=np.zeros((5,3))
i=np.random.random((5,3))
j=np.array([[1,2,3,0,4],[7,5,9,6,8],[5,4,8,6,2]])
k=j.reshape((5,3))
l=np.arange(0,100,10)



In [20]:
print("Array with all Zeros \n",h)
print("Array with random numbers \n",i)
print("Original array : \n",k)
print("\n Reshaped array : \n",j)
print("Array with range value \n",l)




Array with all Zeros 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Array with random numbers 
 [[0.52378274 0.89046846 0.26124406]
 [0.55660786 0.39429591 0.74915619]
 [0.55491414 0.63760224 0.15118066]
 [0.87225478 0.57538754 0.30431509]
 [0.29958489 0.70512316 0.66183298]]
Original array : 
 [[1 2 3]
 [0 4 7]
 [5 9 6]
 [8 5 4]
 [8 6 2]]

 Reshaped array : 
 [[1 2 3 0 4]
 [7 5 9 6 8]
 [5 4 8 6 2]]
Array with range value 
 [ 0 10 20 30 40 50 60 70 80 90]


In [21]:
flat=j.flatten()
print("Flattend array :",flat)

Flattend array : [1 2 3 0 4 7 5 9 6 8 5 4 8 6 2]


In [22]:
print("No.of dimensions: ",j.ndim)

No.of dimensions:  2


In [23]:
print("Shape of the array: ",j.shape)

Shape of the array:  (3, 5)


In [24]:
print("\n Array element type ",j.dtype)


 Array element type  int32


In [31]:
newtype=j.astype('f')
print("\n Convert array element :\n",newtype)
print(" Converted array type : ",newtype.dtype)


 Convert array element :
 [[1. 2. 3. 0. 4.]
 [7. 5. 9. 6. 8.]
 [5. 4. 8. 6. 2.]]
 Converted array type :  float32


In [41]:
print("Size of the array: ",j.size)

Size of the array:  15


In [36]:
lj=len(j)
print(lj)

3
